services:
  - type: web
    name: Fortis-cleaning
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
